### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by ghost** [axos88/rainloop-plugin-vacation-settings-tab#2]
Hello!

I had test the plugin today but I had one problem with the UPDATE request, I use the default request : 

UPDATE autoreply SET active=:active, subject=:subject, body=:msgbody, date_start=:date_start, date_end=:date_end W    HERE local=:local AND domain=:domain

My database:

mysql> DESCRIBE autoreply;
+------------+--------------+------+-----+---------+-------+
| Field      | Type         | Null | Key | Default | Extra |
+------------+--------------+------+-----+---------+-------+
| id         | int(11)      | NO   | PRI | NULL    |       |
| active     | varchar(10)  | YES  |     | NULL    |       |
| subject    | varchar(100) | YES  |     | NULL    |       |
| body       | varchar(255) | YES  |     | NULL    |       |
| date_start | date         | YES  |     | NULL    |       |
| date_end   | date         | YES  |     | NULL    |       |
| local      | varchar(50)  | YES  |     | NULL    |       |
| domain     | varchar(50)  | YES  |     | NULL    |       |
+------------+--------------+------+-----+---------+-------+

When I manually add value with cli, the plugin displayed the good values, so select is OK, but when i want update the value, the save button become red and value don't change in database.

I enabling loggin in mysql and the script seems don't do any request:

151201 16:35:31    62 Connect   root@localhost on vacation
           62 Quit

Can you help me, please ?

**Comment by ftoledo** [comment]
you "W HERE" have a space ?

**Comment by ghost** [comment]
Yes sorry but is juste copy'n'past fail..is not my problem :-(

**Comment by ftoledo** [comment]
Maybe you can activate the logging function in the application.ini file from rainloop.
Also, the :msg_body is not a parameter i think that just be ":body" (al least in the latest git code)

**Comment by axos88** [comment]
Anything in the php error log? Can you trace the ajax request in your browser?

**Comment by ghost** [comment]
@ftoledo have solution, is just :msg_body.. Sorry for the ignorance. You can close the issue.
