### ISSUE TITLE
DB Setup

### ISSUE THREAD

**Issue by eyzae** [axos88/rainloop-plugin-vacation-settings-tab#7]
Maybe not so much an issue but a misunderstanding on my part.  Is there supposed to be a database and table set up already and this plugin is using that database/table?  Or is there a script that I can run to set up the database/table?

Sorry if I don't quite understand.  I have the plugin showing up as AutoReply, and I can go in and set Enabled, Start Date, End Date, Subject, and Body, but clicking Save turns the button red, and I'm assuming it's because there is no 'autoreply' table set up in the database (rainloop) I entered in the plugin section.

**Comment by eyzae** [comment]
I'm not sure how to delete my "Issue" but I just copied the database design from a closed issue where the person issued a 'describe' on the table.  I can now Enable the AutoReply and it saves everything to the database (I wish the Start Date and End Date were calendar options instead of manually typing in dates) but the AutoReply doesn't seem to work.  When I send an email to this account, it shows up in my Inbox (in Rainloop) but nothing is sent back to the sending emailing account. (I hope that made sense).

**Comment by axos88** [comment]
Yes, the database should already be set up. These are just queries that should be run against that

**Comment by axos88** [comment]
Hmm. I'll have to take a look at this. been a while since any of our users used the plugin

**Comment by axos88** [comment]
Do you have an autoresponder set up on your mail server? This won't magically start to work by installing the plugin in rainloop. This can only be used to configure the autoresponder in your mail server, if it reads its configuration from a database.

**Comment by eyzae** [comment]
Hi, you're right.  I was unaware that an autoresponder had to be set up on my mail server, and this plugin would utilize that ability.  I will look in to that issue first and then I can only imagine this plugin will start working.

Thanks for helping me out.
